# {{- if eq .Values.controller.rbacProxy.enable true }}
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   labels:
#     app.kubernetes.io/name: clusterrole
#     app.kubernetes.io/instance: metrics-reader
#     app.kubernetes.io/component: kube-rbac-proxy
#     app.kubernetes.io/created-by: {{ .Release.Name }}
#     app.kubernetes.io/part-of: {{ .Release.Name }}
#   name: {{ .Release.Name }}-metrics-reader
# rules:
# - nonResourceURLs:
#   - "/metrics"
#   verbs:
#   - get
# {{- end }}
