{{- if eq .Values.providers.github.enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-github
  labels:
    control-plane: provider-github
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: provider-github
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      control-plane: provider-github
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: provider-github
    spec:
      {{- if .Values.providers.github.controller.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.providers.github.controller.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - /manager
        {{- if .Values.providers.github.controller.imagePullPolicy }}
        imagePullPolicy: {{ .Values.providers.github.controller.imagePullPolicy }}
        {{- end }}
        args:
        - "--leader-elect"
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=:8443"
        image: ghcr.io/syngit-org/syngit-provider-github:v0.0.1
        env:
        - name: MANAGER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DYNAMIC_WEBHOOK_NAME
          value: {{ .Values.providers.github.controller.dynamicWebhookName }}
        name: manager
        securityContext: {{ toYaml .Values.providers.github.controller.securityContext | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{ toYaml .Values.providers.github.controller.resources | nindent 10 }}
        ports:
        - containerPort: 9443
          name: wbhk-crd-srv
          protocol: TCP
        - containerPort: 9444
          name: wbhk-pusher-srv
          protocol: TCP
      serviceAccountName: {{ .Release.Name }}-providers-controller-manager
      terminationGracePeriodSeconds: 10
      {{- if .Values.providers.github.controller.tolerations }}
      tolerations: {{ toYaml .Values.providers.github.controller.tolerations | nindent 8 }}
      {{- end }}
{{- end }}