{{- if .Release.IsUpgrade -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syngit-api-group-conversion
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  name: syngit-api-group-conversion
rules:
- apiGroups:
  - syngit.io
  - syngit.syngit.io
  resources:
  - remotesyncers
  - remotesyncers/status
  - remoteusers
  - remoteusers/status
  - remoteuserbindings
  - remoteuserbindings/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syngit-api-group-conversion
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syngit-api-group-conversion
subjects:
  - kind: ServiceAccount
    name: syngit-api-group-conversion
    namespace: {{ .Release.Namespace }}
{{- end }}