---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Namespace }}-validating-webhook-configuration
  {{- if eq .Values.webhook.certmanager.enable true }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/operator-webhook-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-crd-service
      namespace: {{ .Release.Namespace }}
      path: /validate-syngit-syngit-io-v3alpha3-remoteuser
  failurePolicy: Fail
  name: vremoteuser.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v3alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-crd-service
      namespace: {{ .Release.Namespace }}
      path: /validate-syngit-syngit-io-v3alpha3-remotesyncer
  failurePolicy: Fail
  name: vremotesyncer.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v3alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesyncers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-crd-service
      namespace: {{ .Release.Namespace }}
      path: /reconcile-syngit-remoteuser-owner
  failurePolicy: Fail
  name: vremoteusers-owner.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v3alpha3
    operations:
    - CREATE
    - DELETE
    resources:
    - remoteusers
  sideEffects: None