---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://172.17.0.1:9443/validate-syngit-syngit-io-v1-remoteuser
  failurePolicy: Fail
  name: vremoteuser.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://172.17.0.1:9443/validate-syngit-syngit-io-v1-remotesyncer
  failurePolicy: Fail
  name: vremotesyncer.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesyncers
  sideEffects: None
