---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyVENDQXBXZ0F3SUJBZ0lVUjJ5TDF6R0FNdVdvWTJiTmtBRkNTYVIxR1Zvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRUxNQWtHQTFVRUJoTUNRVlV4R3pBWkJnTlZCQU1NRW5kbFltaHZiMnN0YzJWeWRtbGpaUzFEUVRBZQpGdzB5TkRBM01ESXhPVEUyTlRsYUZ3MHlOVEEzTURJeE9URTJOVGxhTUM0eEN6QUpCZ05WQkFZVEFrRlZNUjh3CkhRWURWUVFEREJaM1pXSm9iMjlyTFhObGNuWnBZMlV0WTJ4cFpXNTBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5S2NHTHUrYlNWZ2tBcXJvV2FRRno1SXhXVTliTXJaRGhmT1FTMjE2SXRHegpKS096VHkxRHBvSksxNk9UR1p2bEhsbTRqRFBQcDRaeWlyRE9hQkFmUE5KSjB0Q3JNZEorWmJrYnJDeDUrSmJjCmtBK3J2MEtGTExpczY4R01Pa0c2NlF2b3VmRDVIVVpjZWpLTUNVMzhiL3RFOUNFUVFQbVEyZVFkeHFhSTJKTWQKb0JldUtGVlAzUkZtMTAyUm9pTXI5YmtzNWhweGdLUzFiV0pqRjNVNXozZFZhUWRhVXE2NmtVT3BtZ3pvU2ZTZgo0L1luZlV0ZkZkUi85MjNKUG43WThrRDZCQVFjWmFnbjhjSEtndXJkUW5YcUEzbEdpbGp3L3M5MEU3SWNadU5OCmhhTTJsMnZOOWVhRjdrcDFCaFUwNHpKbVRTSFY5QjVweEpwYjYwS3Jad0lEQVFBQm80SEdNSUhETUlHQUJnTlYKSFJFRWVUQjNnalJ1WlhjdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG01bGR5MXZjR1Z5WVhSdgpjaTF6ZVhOMFpXMHVjM1pqZ2pseVpYTnZkWEpqWlhNdGFXNTBaWEpqWlhCMGIzSXRkMlZpYUc5dmF5MXpaWEoyCmFXTmxMbTl3WlhKaGRHOXlMWE41YzNSbGJTNXpkbU9IQkt3UkFBRXdIUVlEVlIwT0JCWUVGQW5aQVVRanJXNmEKcW5wY3NJR2RFRVgva0JPSE1COEdBMVVkSXdRWU1CYUFGTzNDT1ord1lZdnpRVUY4L1Z5ak5NOWxyV1o5TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjVITWlGZHdWZWxxbXllcEN2c2ZVb25RbjE1Qkw4VGE1VzluVWRjVFk3CjdTbmhGL3FVbVNKQkZGbEk0b2FIMWZaVW9JVUNqWjlvMG51bkgwZVNhSGM2aGRvczZSaVl5L1Z5SkFBOTlzT2oKZXFQdXc2ZmpjNnNRcWtrWGUvdnRxY3dLb3Z4Zm5TdyttVVFXV1JFN2s2SitpUzZkVUlvYmtpRkV4RFlzNlJUYwplTmgrZFplaU44dDJTbkhpYU1BcWk4Q1NsWEgyL0tZUkcyQWZmdmoxOXVtZmFXUjl0YnhaUDR6SDRSK1Y4Y2FkCmVqVmZMYjBGMGZFZStSMWhSdTJLWTduYnVJRDdKUEVRblFqMDB1djhkNUEwS1pVK3JMbERGbEhXY1VubEZ6ZGsKdWo0T1A2bm9ja2JKUW80V1BtM0tZOThUVVpHeG5DV0F0TWtGT09zSXU1NVMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-syngit-damsien-fr-v1alpha2-remotesyncer
  failurePolicy: Fail
  name: vremotesyncer.kb.io
  rules:
  - apiGroups:
    - syngit.damsien.fr
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesyncers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyVENDQXBXZ0F3SUJBZ0lVUjJ5TDF6R0FNdVdvWTJiTmtBRkNTYVIxR1Zvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRUxNQWtHQTFVRUJoTUNRVlV4R3pBWkJnTlZCQU1NRW5kbFltaHZiMnN0YzJWeWRtbGpaUzFEUVRBZQpGdzB5TkRBM01ESXhPVEUyTlRsYUZ3MHlOVEEzTURJeE9URTJOVGxhTUM0eEN6QUpCZ05WQkFZVEFrRlZNUjh3CkhRWURWUVFEREJaM1pXSm9iMjlyTFhObGNuWnBZMlV0WTJ4cFpXNTBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5S2NHTHUrYlNWZ2tBcXJvV2FRRno1SXhXVTliTXJaRGhmT1FTMjE2SXRHegpKS096VHkxRHBvSksxNk9UR1p2bEhsbTRqRFBQcDRaeWlyRE9hQkFmUE5KSjB0Q3JNZEorWmJrYnJDeDUrSmJjCmtBK3J2MEtGTExpczY4R01Pa0c2NlF2b3VmRDVIVVpjZWpLTUNVMzhiL3RFOUNFUVFQbVEyZVFkeHFhSTJKTWQKb0JldUtGVlAzUkZtMTAyUm9pTXI5YmtzNWhweGdLUzFiV0pqRjNVNXozZFZhUWRhVXE2NmtVT3BtZ3pvU2ZTZgo0L1luZlV0ZkZkUi85MjNKUG43WThrRDZCQVFjWmFnbjhjSEtndXJkUW5YcUEzbEdpbGp3L3M5MEU3SWNadU5OCmhhTTJsMnZOOWVhRjdrcDFCaFUwNHpKbVRTSFY5QjVweEpwYjYwS3Jad0lEQVFBQm80SEdNSUhETUlHQUJnTlYKSFJFRWVUQjNnalJ1WlhjdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG01bGR5MXZjR1Z5WVhSdgpjaTF6ZVhOMFpXMHVjM1pqZ2pseVpYTnZkWEpqWlhNdGFXNTBaWEpqWlhCMGIzSXRkMlZpYUc5dmF5MXpaWEoyCmFXTmxMbTl3WlhKaGRHOXlMWE41YzNSbGJTNXpkbU9IQkt3UkFBRXdIUVlEVlIwT0JCWUVGQW5aQVVRanJXNmEKcW5wY3NJR2RFRVgva0JPSE1COEdBMVVkSXdRWU1CYUFGTzNDT1ord1lZdnpRVUY4L1Z5ak5NOWxyV1o5TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjVITWlGZHdWZWxxbXllcEN2c2ZVb25RbjE1Qkw4VGE1VzluVWRjVFk3CjdTbmhGL3FVbVNKQkZGbEk0b2FIMWZaVW9JVUNqWjlvMG51bkgwZVNhSGM2aGRvczZSaVl5L1Z5SkFBOTlzT2oKZXFQdXc2ZmpjNnNRcWtrWGUvdnRxY3dLb3Z4Zm5TdyttVVFXV1JFN2s2SitpUzZkVUlvYmtpRkV4RFlzNlJUYwplTmgrZFplaU44dDJTbkhpYU1BcWk4Q1NsWEgyL0tZUkcyQWZmdmoxOXVtZmFXUjl0YnhaUDR6SDRSK1Y4Y2FkCmVqVmZMYjBGMGZFZStSMWhSdTJLWTduYnVJRDdKUEVRblFqMDB1djhkNUEwS1pVK3JMbERGbEhXY1VubEZ6ZGsKdWo0T1A2bm9ja2JKUW80V1BtM0tZOThUVVpHeG5DV0F0TWtGT09zSXU1NVMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-syngit-damsien-fr-v1alpha2-remoteuser
  failurePolicy: Fail
  name: vremoteuser.kb.io
  rules:
  - apiGroups:
    - syngit.damsien.fr
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyVENDQXBXZ0F3SUJBZ0lVUjJ5TDF6R0FNdVdvWTJiTmtBRkNTYVIxR1Zvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRUxNQWtHQTFVRUJoTUNRVlV4R3pBWkJnTlZCQU1NRW5kbFltaHZiMnN0YzJWeWRtbGpaUzFEUVRBZQpGdzB5TkRBM01ESXhPVEUyTlRsYUZ3MHlOVEEzTURJeE9URTJOVGxhTUM0eEN6QUpCZ05WQkFZVEFrRlZNUjh3CkhRWURWUVFEREJaM1pXSm9iMjlyTFhObGNuWnBZMlV0WTJ4cFpXNTBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5S2NHTHUrYlNWZ2tBcXJvV2FRRno1SXhXVTliTXJaRGhmT1FTMjE2SXRHegpKS096VHkxRHBvSksxNk9UR1p2bEhsbTRqRFBQcDRaeWlyRE9hQkFmUE5KSjB0Q3JNZEorWmJrYnJDeDUrSmJjCmtBK3J2MEtGTExpczY4R01Pa0c2NlF2b3VmRDVIVVpjZWpLTUNVMzhiL3RFOUNFUVFQbVEyZVFkeHFhSTJKTWQKb0JldUtGVlAzUkZtMTAyUm9pTXI5YmtzNWhweGdLUzFiV0pqRjNVNXozZFZhUWRhVXE2NmtVT3BtZ3pvU2ZTZgo0L1luZlV0ZkZkUi85MjNKUG43WThrRDZCQVFjWmFnbjhjSEtndXJkUW5YcUEzbEdpbGp3L3M5MEU3SWNadU5OCmhhTTJsMnZOOWVhRjdrcDFCaFUwNHpKbVRTSFY5QjVweEpwYjYwS3Jad0lEQVFBQm80SEdNSUhETUlHQUJnTlYKSFJFRWVUQjNnalJ1WlhjdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG01bGR5MXZjR1Z5WVhSdgpjaTF6ZVhOMFpXMHVjM1pqZ2pseVpYTnZkWEpqWlhNdGFXNTBaWEpqWlhCMGIzSXRkMlZpYUc5dmF5MXpaWEoyCmFXTmxMbTl3WlhKaGRHOXlMWE41YzNSbGJTNXpkbU9IQkt3UkFBRXdIUVlEVlIwT0JCWUVGQW5aQVVRanJXNmEKcW5wY3NJR2RFRVgva0JPSE1COEdBMVVkSXdRWU1CYUFGTzNDT1ord1lZdnpRVUY4L1Z5ak5NOWxyV1o5TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjVITWlGZHdWZWxxbXllcEN2c2ZVb25RbjE1Qkw4VGE1VzluVWRjVFk3CjdTbmhGL3FVbVNKQkZGbEk0b2FIMWZaVW9JVUNqWjlvMG51bkgwZVNhSGM2aGRvczZSaVl5L1Z5SkFBOTlzT2oKZXFQdXc2ZmpjNnNRcWtrWGUvdnRxY3dLb3Z4Zm5TdyttVVFXV1JFN2s2SitpUzZkVUlvYmtpRkV4RFlzNlJUYwplTmgrZFplaU44dDJTbkhpYU1BcWk4Q1NsWEgyL0tZUkcyQWZmdmoxOXVtZmFXUjl0YnhaUDR6SDRSK1Y4Y2FkCmVqVmZMYjBGMGZFZStSMWhSdTJLWTduYnVJRDdKUEVRblFqMDB1djhkNUEwS1pVK3JMbERGbEhXY1VubEZ6ZGsKdWo0T1A2bm9ja2JKUW80V1BtM0tZOThUVVpHeG5DV0F0TWtGT09zSXU1NVMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /reconcile-syngit-remoteuser-owner
  failurePolicy: Fail
  name: vremoteusers-owner.kb.io
  rules:
  - apiGroups:
    - syngit.damsien.fr
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    resources:
    - remoteusers
  sideEffects: None
