---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-syngit-syngit-io-v1beta2-remotesyncer
  failurePolicy: Fail
  name: vremotesyncer-v1beta2.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesyncers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-syngit-syngit-io-v1beta2-remoteuser
  failurePolicy: Fail
  name: vremoteuser-v1beta2.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /syngit-v1beta2-remoteuser-association
  failurePolicy: Fail
  name: vremoteusers-association.v1beta2.syngit.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - DELETE
    resources:
    - remoteusers
  sideEffects: None
