---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-syngit-syngit-io-v1alpha4-remotesyncer
  failurePolicy: Fail
  name: vremotesyncer.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesyncers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-syngit-syngit-io-v1alpha4-remoteuser
  failurePolicy: Fail
  name: vremoteuser.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /reconcile-syngit-remoteuser-owner
  failurePolicy: Fail
  name: vremoteusers-owner.kb.io
  rules:
  - apiGroups:
    - syngit.syngit.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - DELETE
    resources:
    - remoteusers
  sideEffects: None
