{{- if .Release.IsUpgrade -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rub-migration
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rub-migration
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rub-migration
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: helm-rub-migration
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - "syngit.io"
  resources:
  - remoteuserbindings
  verbs:
  - update
  - patch
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rub-migration
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: helm-rub-migration
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rub-migration
subjects:
  - kind: ServiceAccount
    name: rub-migration
    namespace: {{ .Release.Namespace }}
{{- end }}
