{{- if or (eq .Values.providers.github.enabled true) (eq .Values.providers.gitlab.enabled true) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}-providers
  name: {{ .Release.Name }}-providers-controller-manager
{{- end }}