{{- if eq .Values.config.defaultExcludedFields.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-excluded-fields
  namespace: {{ .Release.Namespace }}
  labels:
    syngit.io/cluster-default-excluded-fields: "true"
data:
  excludedFields: |
    - metadata.annotations.[kubectl.kubernetes.io/last-applied-configuration]
    - metadata.creationTimestamp
    - metadata.generateName
    - metadata.generation
    - metadata.managedFields
    - metadata.resourceVersion
    - metadata.uid
    - status
{{- end }}