{{- if eq .Values.webhook.certmanager.enable true }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: operator-webhook-cert
spec:
  dnsNames:
  - webhook-crd-service.{{ .Release.Namespace }}.svc
  - webhook-crd-service.{{ .Release.Namespace }}.svc.local
  - syngit-remote-syncer-webhook-service.{{ .Release.Namespace }}.svc
  - syngit-remote-syncer-webhook-service.{{ .Release.Namespace }}.svc.local
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-selfsigned-issuer
  secretName: {{ .Values.webhook.certmanager.certificate.secret }}
{{- end }}