# permissions for end users to view remotetargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: syngit
    app.kubernetes.io/managed-by: kustomize
  name: remotetarget-viewer-role
rules:
- apiGroups:
  - syngit.io
  resources:
  - remotetargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remotetargets/status
  verbs:
  - get
