# permissions for end users to edit remotesyncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remotesyncer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: syngit
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
  name: remotesyncer-editor-role
rules:
- apiGroups:
  - syngit.syngit.io
  resources:
  - remotesyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syngit.syngit.io
  resources:
  - remotesyncers/status
  verbs:
  - get
