# permissions for end users to view remoteusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remoteuser-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: syngit
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
  name: remoteuser-viewer-role
rules:
- apiGroups:
  - syngit.syngit.io
  resources:
  - remoteusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syngit.syngit.io
  resources:
  - remoteusers/status
  verbs:
  - get
