---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remotesyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remotesyncers/finalizers
  verbs:
  - update
- apiGroups:
  - syngit.io
  resources:
  - remotesyncers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - syngit.io
  resources:
  - remoteuserbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remoteuserbindings/finalizers
  verbs:
  - update
- apiGroups:
  - syngit.io
  resources:
  - remoteuserbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - syngit.io
  resources:
  - remoteusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remoteusers/finalizers
  verbs:
  - update
- apiGroups:
  - syngit.io
  resources:
  - remoteusers/status
  verbs:
  - get
  - patch
  - update
