{{- if .Release.IsUpgrade -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-migration
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: post-migration
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: post-migration
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: helm-post-migration
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - ""
  resources:
  - "users"
  - "groups"
  verbs:
  - "impersonate"
- apiGroups:
  - ""
  - "syngit.io"
  resources:
  - "pods"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "syngit.io"
  resources:
  - remoteusers
  verbs:
  - update
  - patch
  - get
  - list
  - watch
- apiGroups:
  - "syngit.io"
  resources:
  - remotetargets
  - remoteuserbindings
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: post-migration
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: helm-post-migration
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: post-migration
subjects:
  - kind: ServiceAccount
    name: post-migration
    namespace: {{ .Release.Namespace }}
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: syngit:post-migration-patch
{{- end }}
