apiVersion: syngit.syngit.io/v1beta2
kind: RemoteUserBinding
metadata:
  labels:
    app.kubernetes.io/name: remoteuserbinding
    app.kubernetes.io/instance: remoteuserbinding-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remoteuserbinding-sample
spec:
  # TODO(user): Add fields here
