# permissions for end users to view remotesyncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remotesyncers-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-remotesyncers-viewer-role
rules:
- apiGroups:
  - syngit.io
  resources:
  - remotesyncers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remotesyncers/status
  verbs:
  - get
