---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Namespace }}-validating-webhook-configuration
  {{- if eq .Values.webhook.certmanager.enable true }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/operator-webhook-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-crd-service
      namespace: {{ .Release.Namespace }}
      path: /validate-syngit-io-v1beta2-remoteuser
  failurePolicy: Fail
  name: vremoteuser.kb.io
  rules:
  - apiGroups:
    - syngit.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-crd-service
      namespace: {{ .Release.Namespace }}
      path: /syngit-v1beta2-remotesyncer-rules-permissions
  failurePolicy: Fail
  name: vremotesyncers-rules-permissions.v1beta2.syngit.io
  rules:
  - apiGroups:
    - syngit.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - remotesyncers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-crd-service
      namespace: {{ .Release.Namespace }}
      path: /validate-syngit-io-v1beta2-remotesyncer
  failurePolicy: Fail
  name: vremotesyncer.kb.io
  rules:
  - apiGroups:
    - syngit.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesyncers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-crd-service
      namespace: {{ .Release.Namespace }}
      path: /syngit-v1beta2-remoteuser-association
  failurePolicy: Fail
  name: vremoteusers-association.v1beta2.syngit.io
  rules:
  - apiGroups:
    - syngit.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - remoteusers
  sideEffects: None