---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-manager-role
rules:
# Any resources can be pushed to the git repo.
# The scope depends but the controller
#  needs to be able to get,list,watch any of them
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# Create and patch events related to kgio objects in any namespace
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gitremotes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gitremotes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings/finalizers
  verbs:
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors/finalizers
  verbs:
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors/status
  verbs:
  - get
  - patch
  - update
