apiVersion: syngit.syngit.io/v1alpha2
kind: RemoteSyncer
metadata:
  labels:
    app.kubernetes.io/name: remotesyncer
    app.kubernetes.io/instance: remotesyncer-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remotesyncer-sample
  namespace: test
spec:
