name: Tests

on:
  # run it on push to the default repository branch
  push:
  pull_request:

jobs:

  tests-build-deploy:
    name: Build & deploy tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up KinD
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.23.0
        cluster_name: syngit-dev-cluster

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Run tests
      run: make test-build-deploy

  tests-e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up KinD
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.23.0
        cluster_name: syngit-dev-cluster

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Install kubernetes binaries
      run: |
        make envtest
        ./bin/setup-envtest-latest use --bin-dir ./bin

    - name: Run tests
      run: make test-e2e